name: 'Compile Mermaid in Markdown'

on:
  push:
    paths:
      - '**/*.mermaid'
      - '**/*.mmd'
      - '**/*.md'
  # Refresh the red line that shows "when/where" we are now
  schedule:
    - cron: "0 0 */5 * *"
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' -e '.*\.mermaid$' | xargs)"
    - name: mermaid files changed
      run: |
        echo ${{ steps.getfile.outputs.files }}
    - name: compile mermaid
      uses: neenjaw/compile-mermaid-markdown-action@master
      with:
        files: ${{ steps.getfile.outputs.files }}
        output: 'output'
      env:
        HIDE_CODEBLOCKS: 1
        ABSOLUTE_IMAGE_LINKS: 1

    - name: show changes
      run: |
        git status

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Action: compile-mermaid" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
